<?php
/**
 * Plugin Name: register-acf-blocks
 * Plugin URI: https://ronnyfreites.com/
 * Description: This plugin is to register acf blocks.
 * Version: 0.1
 * Author: your-name
 * Author URI: https://ronnyfreites.com/
 **/

add_action("acf/init", "register_acf_blocks_init");
function register_acf_blocks_init()
{
  // check function exists
  if (function_exists("acf_register_block")) {
    function render_block_name_preview($block)
    {
      $block_name = str_replace("acf/", "", $block["name"]);
      echo "<p> This block renders " . $block_name . "</p>";
    }

    acf_register_block([
      "name" => "hero-block",
      "title" => __("Hero"),
      "description" => __("A custom hero block."),
      "render_callback" => "render_block_name_preview",
      "category" => "theme",
      "icon" => "format-image",
    ]);

    acf_register_block([
      "name" => "slider-block",
      "title" => __("Slider"),
      "description" => __("A custom slider block."),
      "render_callback" => "render_block_name_preview",
      "category" => "theme",
      "icon" => "images-alt",
    ]);

    acf_register_block([
      "name" => "testimonial-block",
      "title" => __("Testimonial"),
      "description" => __("A custom testimonial block."),
      "render_callback" => "render_block_name_preview",
      "category" => "theme",
      "icon" => "testimonial",
    ]);

    acf_register_block([
      "name" => "image-text-block",
      "title" => __("Image Text"),
      "description" => __("A custom image text block."),
      "render_callback" => "render_block_name_preview",
      "category" => "theme",
      "icon" => "dashicons-admin-generic",
    ]);

    acf_register_block([
      "name" => "anchor-link-block",
      "title" => __("Anchor Link"),
      "description" => __("Anchor link block."),
      "render_callback" => "render_block_name_preview",
      "category" => "theme",
      "icon" => "dashicons-admin-links",
    ]);
  }
}

add_action("acf/include_fields", function () {
  if (!function_exists("acf_add_local_field_group")) {
    return;
  }

  acf_add_local_field_group([
    "key" => "group_66d66370396f8",
    "title" => "ANCHOR-LINK",
    "fields" => [
      [
        "key" => "field_66d663707ef64",
        "label" => "Anchor Link ID",
        "name" => "anchor_link_id",
        "aria-label" => "",
        "type" => "text",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "maxlength" => "",
        "placeholder" => "",
        "prepend" => "",
        "append" => "",
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "anchorLinkId",
        "graphql_non_null" => 0,
      ],
    ],
    "location" => [
      [
        [
          "param" => "block",
          "operator" => "==",
          "value" => "acf/anchor-link-block",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
    "show_in_rest" => 0,
    "show_in_graphql" => 1,
    "graphql_field_name" => "anchorId",
    "map_graphql_types_from_location_rules" => 0,
    "graphql_types" => "",
  ]);

  acf_add_local_field_group([
    "key" => "group_66d3a72771502",
    "title" => "HERO-BLOCK",
    "fields" => [
      [
        "key" => "field_66d3a727d00d9",
        "label" => "MAIN HERO IMAGE",
        "name" => "main_hero_image",
        "aria-label" => "",
        "type" => "image",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "return_format" => "url",
        "library" => "all",
        "min_width" => "",
        "min_height" => "",
        "min_size" => "",
        "max_width" => "",
        "max_height" => "",
        "max_size" => "",
        "mime_types" => "",
        "allow_in_bindings" => 0,
        "preview_size" => "medium",
      ],
      [
        "key" => "field_66d3a777d00da",
        "label" => "MAIN HERO MESSAGE",
        "name" => "main_hero_message",
        "aria-label" => "",
        "type" => "text",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "maxlength" => "",
        "allow_in_bindings" => 0,
        "placeholder" => "",
        "prepend" => "",
        "append" => "",
      ],
    ],
    "location" => [
      [
        [
          "param" => "block",
          "operator" => "==",
          "value" => "acf/hero-block",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
    "show_in_rest" => 0,
    "show_in_graphql" => 1,
    "graphql_field_name" => "heroBlock",
    "map_graphql_types_from_location_rules" => 0,
    "graphql_types" => "",
  ]);

  acf_add_local_field_group([
    "key" => "group_66d5231dec130",
    "title" => "IMAGE-TEXT-BLOCK",
    "fields" => [
      [
        "key" => "field_66d5231e72e19",
        "label" => "Image",
        "name" => "image",
        "aria-label" => "",
        "type" => "image",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "return_format" => "id",
        "library" => "all",
        "min_width" => "",
        "min_height" => "",
        "min_size" => "",
        "max_width" => "",
        "max_height" => "",
        "max_size" => "",
        "mime_types" => "",
        "preview_size" => "medium",
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "image",
      ],
      [
        "key" => "field_66d5235772e1a",
        "label" => "Text",
        "name" => "text",
        "aria-label" => "",
        "type" => "textarea",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "default_value" => "",
        "maxlength" => "",
        "rows" => "",
        "placeholder" => "",
        "new_lines" => "",
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "text",
        "graphql_non_null" => 0,
      ],
      [
        "key" => "field_66d5364abea39",
        "label" => "Text Align",
        "name" => "text_align",
        "aria-label" => "",
        "type" => "select",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "choices" => [
          "left" => "left",
          "right" => "right",
        ],
        "default_value" => false,
        "return_format" => "value",
        "multiple" => 0,
        "allow_null" => 0,
        "ui" => 0,
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "textAlign",
        "graphql_non_null" => 0,
        "ajax" => 0,
        "placeholder" => "",
      ],
    ],
    "location" => [
      [
        [
          "param" => "block",
          "operator" => "==",
          "value" => "acf/image-text-block",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
    "show_in_rest" => 0,
    "show_in_graphql" => 1,
    "graphql_field_name" => "imageMediaBlock",
    "map_graphql_types_from_location_rules" => 0,
    "graphql_types" => "",
  ]);

  acf_add_local_field_group([
    "key" => "group_66d536c334729",
    "title" => "SLIDER-BLOCK",
    "fields" => [
      [
        "key" => "field_66d536c339e1a",
        "label" => "Slider Row",
        "name" => "slider_row",
        "aria-label" => "",
        "type" => "repeater",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "layout" => "block",
        "pagination" => 0,
        "min" => 0,
        "max" => 0,
        "collapsed" => "",
        "button_label" => "Add Row",
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "sliderRow",
        "graphql_non_null" => 0,
        "rows_per_page" => 20,
        "sub_fields" => [
          [
            "key" => "field_66d536c33b9cc",
            "label" => "SlideImage",
            "name" => "slideimage",
            "aria-label" => "",
            "type" => "image",
            "instructions" => "",
            "required" => 0,
            "conditional_logic" => 0,
            "wrapper" => [
              "width" => "",
              "class" => "",
              "id" => "",
            ],
            "return_format" => "id",
            "library" => "all",
            "min_width" => "",
            "min_height" => "",
            "min_size" => "",
            "max_width" => "",
            "max_height" => "",
            "max_size" => "",
            "mime_types" => "",
            "preview_size" => "medium",
            "show_in_graphql" => 1,
            "graphql_description" => "",
            "graphql_field_name" => "slideimage",
            "parent_repeater" => "field_66d536c339e1a",
          ],
        ],
      ],
    ],
    "location" => [
      [
        [
          "param" => "block",
          "operator" => "==",
          "value" => "acf/slider-block",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
    "show_in_rest" => 0,
    "show_in_graphql" => 1,
    "graphql_field_name" => "sliderBlock",
    "map_graphql_types_from_location_rules" => 0,
    "graphql_types" => "",
  ]);

  acf_add_local_field_group([
    "key" => "group_66d536a819967",
    "title" => "TESTIMONIAL-BLOCK",
    "fields" => [
      [
        "key" => "field_66d536a8224f8",
        "label" => "Testimony Row",
        "name" => "testimony_row",
        "aria-label" => "",
        "type" => "repeater",
        "instructions" => "",
        "required" => 0,
        "conditional_logic" => 0,
        "wrapper" => [
          "width" => "",
          "class" => "",
          "id" => "",
        ],
        "layout" => "block",
        "pagination" => 0,
        "min" => 0,
        "max" => 0,
        "collapsed" => "",
        "button_label" => "Add Row",
        "show_in_graphql" => 1,
        "graphql_description" => "",
        "graphql_field_name" => "testimonyRow",
        "graphql_non_null" => 0,
        "rows_per_page" => 20,
        "sub_fields" => [
          [
            "key" => "field_66d536a8240cc",
            "label" => "Testimony",
            "name" => "testimony",
            "aria-label" => "",
            "type" => "text",
            "instructions" => "",
            "required" => 0,
            "conditional_logic" => 0,
            "wrapper" => [
              "width" => "",
              "class" => "",
              "id" => "",
            ],
            "default_value" => "",
            "maxlength" => "",
            "placeholder" => "",
            "prepend" => "",
            "append" => "",
            "show_in_graphql" => 1,
            "graphql_description" => "",
            "graphql_field_name" => "testimony",
            "graphql_non_null" => 0,
            "parent_repeater" => "field_66d536a8224f8",
          ],
          [
            "key" => "field_66d536a82446f",
            "label" => "Picture",
            "name" => "picture",
            "aria-label" => "",
            "type" => "image",
            "instructions" => "",
            "required" => 0,
            "conditional_logic" => 0,
            "wrapper" => [
              "width" => "",
              "class" => "",
              "id" => "",
            ],
            "return_format" => "id",
            "library" => "all",
            "min_width" => "",
            "min_height" => "",
            "min_size" => "",
            "max_width" => "",
            "max_height" => "",
            "max_size" => "",
            "mime_types" => "",
            "preview_size" => "medium",
            "show_in_graphql" => 1,
            "graphql_description" => "",
            "graphql_field_name" => "picture",
            "parent_repeater" => "field_66d536a8224f8",
          ],
          [
            "key" => "field_66d536a82486a",
            "label" => "Author",
            "name" => "author",
            "aria-label" => "",
            "type" => "text",
            "instructions" => "",
            "required" => 0,
            "conditional_logic" => 0,
            "wrapper" => [
              "width" => "",
              "class" => "",
              "id" => "",
            ],
            "default_value" => "",
            "maxlength" => "",
            "placeholder" => "",
            "prepend" => "",
            "append" => "",
            "show_in_graphql" => 1,
            "graphql_description" => "",
            "graphql_field_name" => "author",
            "graphql_non_null" => 0,
            "parent_repeater" => "field_66d536a8224f8",
          ],
        ],
      ],
    ],
    "location" => [
      [
        [
          "param" => "block",
          "operator" => "==",
          "value" => "acf/testimonial-block",
        ],
      ],
    ],
    "menu_order" => 0,
    "position" => "normal",
    "style" => "default",
    "label_placement" => "top",
    "instruction_placement" => "label",
    "hide_on_screen" => "",
    "active" => true,
    "description" => "",
    "show_in_rest" => 0,
    "show_in_graphql" => 1,
    "graphql_field_name" => "testimonialBlock",
    "map_graphql_types_from_location_rules" => 0,
    "graphql_types" => "",
  ]);
});
